### ISSUE TITLE
Remove Training Wheels

### ISSUE THREAD

**Issue by SonnyBrooks** [evanjb240/AngularCSharpTemplate-Client#1]
Many TS(training-wheels script) files. Please replace.

**Comment by SonnyBrooks** [comment]
Maybe @joeythomaschaske can help you?

**Comment by joeythomaschaske** [comment]
lolz

**Comment by SonnyBrooks** [comment]
Training wheels can be useful for anyone, not just noobs. Closing because training wheels are actually pretty cool.
